# Generated by Django 4.0.3 on 2022-03-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tio_Patinhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dental_sorriso',
            options={'verbose_name': 'Usuario do plano', 'verbose_name_plural': 'Dental Sorriso'},
        ),
        migrations.AlterModelOptions(
            name='mente_sa_corpo_sao',
            options={'verbose_name': 'Usuario do plano', 'verbose_name_plural': 'Mente sã, Corpo São'},
        ),
        migrations.AlterModelOptions(
            name='pampulha_intermedica',
            options={'verbose_name': 'Usuario do plano', 'verbose_name_plural': 'Pampulha Intermédica'},
        ),
    ]
