# Generated by Django 4.0.3 on 2022-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dental_Sorriso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('peso', models.CharField(blank=True, max_length=10, verbose_name='Peso (kg)')),
                ('altura', models.CharField(blank=True, max_length=200, verbose_name='Altura (cm)')),
            ],
        ),
        migrations.CreateModel(
            name='Norte_Europa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('data', models.DateField(verbose_name='Data de Admissão')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
            ],
        ),
    ]
