# Generated by Django 4.0.3 on 2022-03-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acme_Ceo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dental_sorriso',
            options={'verbose_name': 'Dental_Sorriso', 'verbose_name_plural': 'Dental_Sorrisos'},
        ),
    ]
